version: "3.3"

volumes:
  postgresql-volume:  # pointing volume to db

services:
  db:
    ports:
      - "5435:5432"  # pointing port 5435 from our environment to postgre default port 5432 in docker
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'djcrmuser'
      POSTGRES_DB: 'djcrm'
      POSTGRES_PORT: 5432
    user: postgres
  
  djangoapp:
    ports:
      - "9000:9000" # we'll use port 9000 for django
    environment:
      - DJANGO_ENV=development
      - DB_NAME=djcrm
      - DB_USER=djcrmuser
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432