version: "3.9"

services:
  djangoapp:
    ports:
      - "80:9000" # we'll use port 5000 for django
    environment:
      - DJANGO_ENV=production
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=localhost
      - DB_PORT=5432

  db:
    ports:
      - "5435:5432"  # pointing port 5435 from our environment to postgre default port 5432 in docker
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'djcrmuser'
      POSTGRES_DB: 'djcrm'
      POSTGRES_PORT: 5432
    user: postgres